### ISSUE TITLE
Alist example not quite right

### ISSUE THREAD

**Issue by franburstall** [caiorss/Emacs-Elisp-Programming#12]
Hi,

Yr function plist->alist creates a list of lists rather than a list of cons cells.  Should be something like:

    (defun plist->alist (plist)
      (if (null plist)
          '()
          (cons
           (cons (car plist) (cadr plist))
          (plist->alist (cddr plist)))))

---Fran

**Comment by caiorss** [comment]
You can actually, have association lists as lists of two elements or list of cons cells.  It works with both, your functions and mine are correct. Here a example:

```elisp
ELISP> (defun plist->alist (plist)
  (if (null plist)
      '()
      (cons
       (list (car plist) (cadr plist))
       (plist->alist (cddr plist)))))
plist->alist
ELISP> 
ELISP> (plist->alist (list :x 10 :y 20 :name "point"))
((:x 10)
 (:y 20)
 (:name "point"))

ELISP> (assoc :x (plist->alist (list :x 10 :y 20 :name "point")))
(:x 10)

ELISP> (assoc :y (plist->alist (list :x 10 :y 20 :name "point")))
(:y 20)

ELISP> 
```

The problem with list of cons cells is that in the first code below the it becomes a single list, which makes hard to distinguish between a "list" or cons cell (Every list is a cons cell, of the head element and the rest of the list).

```elisp
ELISP> (cons :x '(1 2 3 4))
(:x 1 2 3 4)

ELISP> '(:x . (1 2 3 4))
(:x 1 2 3 4)

ELISP> (list :x '(1 2 3 4))
(:x
 (1 2 3 4))
```

**Comment by franburstall** [comment]
OK, I agree: should have read the manual more carefully.  However, as the
manual says, reverse lookup with rassoc will fail on your version:

ELISP> (setq my-alist '((:a . 1) (:b . 2)))
((:a . 1)
 (:b . 2))

ELISP> (setq yr-alist '((:a 1) (:b 2)))
((:a 1)
 (:b 2))

ELISP> (rassoc 2 my-alist)
(:b . 2)

ELISP> (rassoc 2 yr-alist)
nil

---Fran

**Comment by caiorss** [comment]
Thanks for the contribution. Ok I will add your function, but I will call this list of cons pair 
of clist '((a . b) (x . y)) and the lists of two elements of alist to reduce the ambiguity '((a b) (x y)).
