### ISSUE TITLE
(position) not defined

### ISSUE THREAD

**Issue by goosetherumfoodle** [caiorss/Emacs-Elisp-Programming#2]
Does (position) need to be defined by some library? 
```
ELISP> (position 2 '(5 6 7 8))
*** Eval error ***  Symbol's function definition is void: position
```
I'm using emacs version ``24.4.90.1``

**Comment by xuchunyang** [comment]
Your Emacs is newer than 24.3, according to http://emacs.stackexchange.com/a/10494/3889, you should use `cl-position` from the `cl-lib` library instead, load that library by evaluating `(require 'cl-lib)` if not already.

**Comment by goosetherumfoodle** [comment]
Thanks @xuchunyang
